### ISSUE TITLE
iOS Version

### ISSUE THREAD

**Issue by NathanWalker** [triniwiz/nativescript-splashscreen#1]
Some interesting pods to base iOS version from:
- https://github.com/terrybu/TBVideoSplashScreen
- https://github.com/callumboddy/CBZSplashView (Twitter style splash screen)
- https://github.com/movielala/VideoSplashKit

**Comment by triniwiz** [comment]
Interesting stuff

**Comment by triniwiz** [comment]
Added https://github.com/triniwiz/nativescript-splashscreen/commit/c0d4acef6e14ad98e03edb531023b31ee4cec24e
