### ISSUE TITLE
Release app build start fails

### ISSUE THREAD

**Issue by terhoraj** [triniwiz/nativescript-splashscreen#10]
This plugin messed things up very badly for some reason.

Debug builds worked every time but when release build were made and uploaded google play, nothing worked anymore. Animation was working fine but it could not launch nativescript application view and app failed.

Have you tested release builds with this plugin before?

**Comment by triniwiz** [comment]
versions before 2.3 worked fine i need to do an update to fix the issues with 2.3 and yes the plugin works fine in release builds e.g [WeatheRecipes ](https://play.google.com/store/apps/details?id=co.fitcom.WeatheRecipes), [ShoutOutPlay](https://play.google.com/store/apps/details?id=com.wwwalkerrun.ShoutOutPlay), [NativeScript Weather Cards](https://play.google.com/store/apps/details?id=org.joshdsommer.weathercards)

**Comment by triniwiz** [comment]
Update to 2.2.0 the problem has been resolved https://github.com/triniwiz/nativescript-splashscreen/commit/7faf063e0255b22bbe5810d2e7e52041d4a24495
