### ISSUE TITLE
Fail to set splash_title

### ISSUE THREAD

**Issue by abolinhas** [triniwiz/nativescript-splashscreen#12]
Hi,
I'm trying set the splash_title but always get "NativeScript Splash"

Workaround:
Intead change the title name in app/App_Resources/Android/values/splash_settings.xml need to change in app/platforms/android/src/F1/res/values/splash_settings.xml to get it work

**Comment by triniwiz** [comment]
did you rebuild after changing the file e.g `tns run` ?

**Comment by abolinhas** [comment]
Yes,
tns build android and tns run android

**Comment by abolinhas** [comment]
The same happens for colors, you need to change in app/platforms/android/src/F1/res/values/material_colors.xml instead app//App_Resources/Android/values/material_colors.xml

**Comment by triniwiz** [comment]
I'll update the plugin and docs to make things easier

**Comment by abolinhas** [comment]
Cool,  keep me posted about it

**Comment by triniwiz** [comment]
Fixed in https://github.com/triniwiz/nativescript-splashscreen/commit/3d4764031c5f11fce3e5f6c3c32998b7014679b1 update the `const title` to change the splashscreen title
