### ISSUE TITLE
New NS update --> splash crashes

### ISSUE THREAD

**Issue by terhoraj** [triniwiz/nativescript-splashscreen#13]
After updating to newest nativescript version, once again app crashes at splash on animation finished event. Maybe NS has changed some parameters with main activity.

This was my last time I used this plugin.

**Comment by triniwiz** [comment]
can you paste your `SplashScreen.js` & the crash log because i am sure it is not updated

**Comment by triniwiz** [comment]
Remove your SplashScreen.js then update the plugin to `2.3` to fix your issue
