### ISSUE TITLE
Cannot Find "Co.fitcom.SplashScreen"

### ISSUE THREAD

**Issue by NejiHyuuga** [triniwiz/nativescript-splashscreen#17]
[AndroidManifest.zip](https://github.com/triniwiz/nativescript-splashscreen/files/1685875/AndroidManifest.zip)

Hi ,

I was working for the splash screen animation for my nativescript angular app and found this plugin.
I have added the plugin and made changes in my AndroidManifest.xml. I am getting an Exception.

 Unable to instantiate activity ComponentInfo{com.tns.NativeScriptApplication/co.fitcom.SplashScreen}: java.lang.ClassNotFoundException: Didn't find class "co.fitcom.SplashScreen" on path: DexPathList[[zip file "/data/app/com.tns.NativeScriptApplication-1/base.apk"],nativeLibraryDirectories=[/data/app/com.tns.NativeScriptApplication-1/lib/arm, /data/app/com.tns.NativeScriptApplication-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]

Could you please help me on this. My Files are attached here.

Regards,
Neji

**Comment by mrazahasan** [comment]
Same issue.

**Comment by cdvillagra** [comment]
Hey you guys!

Try click in 'Clean' on Android project, and after you can compile =]

**Comment by wanpeng2008** [comment]
Same issue for angular with --env.aot run option. 
i try to empty the "platforms" folder and re-compile it. Still the same error.

**Comment by CentroneF** [comment]
Still having the same issue. I tried to remove and add platform, remove and add plugin but nothing. do you remember how did you fix the issue?
