### ISSUE TITLE
Code compilation errors

### ISSUE THREAD

**Issue by vinayhfs** [triniwiz/nativescript-splashscreen#2]
Followed you instructions as mentioned in document but getting errors in file app/SplashScreen.ts
Errors for all 'com' and 'org' word example at first  line of class
 extends com.viksaa.sssplash.lib.activity.AwesomeSplash
trying on windows for android version ( with typescript)

**Comment by triniwiz** [comment]
I will update the plugin the complier is complaining because of the missing typings if you want to bypass this error for now change `"noEmitOnError": true` to `false` in the tsconfig.json

**Comment by robertonic** [comment]
I get the same errors and changing  "noEmitOnError"  to `false` in tsconfig.json makes no difference. 

app/SplashScreen.ts(12,41): error TS2304: Cannot find name 'org'.
app/SplashScreen.ts(14,37): error TS2304: Cannot find name 'com'.
app/SplashScreen.ts(15,37): error TS2304: Cannot find name 'com'.
app/SplashScreen.ts(21,37): error TS2304: Cannot find name 'org'.
app/SplashScreen.ts(23,50): error TS2304: Cannot find name 'com'.
app/SplashScreen.ts(27,23): error TS2304: Cannot find name 'com'.
app/SplashScreen.ts(27,79): error TS2304: Cannot find name 'org'.
app/SplashScreen.ts(30,40): error TS2304: Cannot find name 'org'.
app/SplashScreen.ts(33,44): error TS2304: Cannot find name 'com'.
app/SplashScreen.ts(38,28): error TS2304: Cannot find name 'android'.
app/SplashScreen.ts(38,51): error TS2304: Cannot find name 'com'.
app/SplashScreen.ts(38,122): error TS2304: Cannot find name 'com'.
app/SplashScreen.ts(39,25): error TS2304: Cannot find name 'android'.
app/SplashScreen.ts(40,9): error TS2304: Cannot find name 'com'.

**Comment by triniwiz** [comment]
Update to `2.1.0` i'm closing this if you have any problems feel free to reopen
