### ISSUE TITLE
Android Status Bar color

### ISSUE THREAD

**Issue by terhoraj** [triniwiz/nativescript-splashscreen#6]
I was using nativescript-statusbar plugin which set android status bar color for my liking. Now this overrides it and it is not working anymore. Can I set status bar color from this plugin somewhere ?

**Comment by triniwiz** [comment]
I will need to do some tests

**Comment by terhoraj** [comment]
I try doing too, I'll post my results if there is any. Thanks for your help in advance!

**Comment by terhoraj** [comment]
This is not a solution but it's a workaround. Adding `<item name="colorPrimaryDark">#ur_color</item>`
at App_Resources -> values -> styles.xml and values-v21 -> styles.xml App theme section works.

**Comment by triniwiz** [comment]
Did some updates the splashscreen no need to add any color to the status bar https://github.com/triniwiz/nativescript-splashscreen/commit/3d4764031c5f11fce3e5f6c3c32998b7014679b1
