### ISSUE TITLE
Cannot find module 'nativescript-splashscreen'

### ISSUE THREAD

**Issue by 1N50MN14** [triniwiz/nativescript-splashscreen#8]
First thanks for the plugin!

Followed the instructions, still getting this error. Tried to readd the platforms, didn't help. I'm on NativeScript 2.2.

Any ideas?

Thanks

**Comment by triniwiz** [comment]
What platform ?

**Comment by 1N50MN14** [comment]
Both Android and iOS..

**Comment by 1N50MN14** [comment]
Also happens on a newly created project, cloned the repo and ran the demo, same error.

**Comment by chathurangac** [comment]
In NativeScript 2.2 there are some changes to the directory hierarchy. Check the bottom part of this [Pull Request](https://github.com/tjvantoll/nativescript-plugin-seed/commit/e6d6b5709aa936043a28916e0d94b748c97dab77)

I think this plugin has to be updated to support NativeScript latest version. I can also confirm the demo is not working as it is. (I am trying to figure out the problem.)

**Comment by triniwiz** [comment]
@chathurangac i started the update just waiting on more thing before pushing it out

**Comment by triniwiz** [comment]
Everything should be fine now in https://github.com/triniwiz/nativescript-splashscreen/commit/7faf063e0255b22bbe5810d2e7e52041d4a24495
